name: greem
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - dacite
  - codecarbon
  - ipython
  - jupyter
  - numpy
  - pandas
  - pydantic
  - pytest
  - pip

  - pip:
      - opencv-python
      - yt-dlp
      - nvitop
