name: greem
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - dacite
  # - pynvml
  - codecarbon
  - ipython
  - jupyter
  - numpy
  - pandas
  - pydantic
  # - watchdog
  - pip

  - pip:
      - opencv-python
      - yt-dlp
      - nvitop
