name: gaia-tools
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.10
  - dacite
  - codecarbon
  - ipython
  - jupyter
  - numpy
  - pandas
  - pip
 
  - pip:
    - opencv-python
    - yt-dlp
    - nvitop
    - pynvml

