name: greem
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - dacite
  - codecarbon
  - ipython
  - matplotlib
  - seaborn
  - jupyter
  - numpy
  - pandas
  - polars
  - pydantic
  - pytest
  - pip
  - pyarrow

  - pip:
      - opencv-python
      - yt-dlp
      - nvitop
