
scaling_enabled: True

scaling_resolutions: 
  - height: 540
    width: 960

framerate:
  # - 15
  - 24
  - 30

decoding_sleep: 0.1

decode_all_videos: True

encoding_codecs:
  - h264
  # - h265

encoding_preset:
  - medium
  # - slow

encoding_renditions:
  - bitrate: 145
    height: 234
    width: 416
  - bitrate: 1100
    height: 432
    width: 768
